language: python
python:
  - "3.7-dev"
cache: pip
install:
  - pip install -r requirements.txt
script:
  - python3 RSOI_1/manage.py test RSOI_1
deploy:
  provider: heroku
  api_key:
    secure: 001f65be-5485-4de9-9a70-26958e4305e0
  on:
    repo: Blati/RSOI_1